export const articulos = [
    {
      id: '1',
      codigo: '',
      nombre: 'MDF Crudo 18mm',
      rubro:'Maderas',
      familia: 'Placas',
      categoria: 'MDF',
      subcategoria: '18mm',
      precio: 120,
      img: '',
      img_tumb: ''	  	  
    },
    {
      id: '2',
      codigo: '',
      nombre: 'MDF Crudo 15mm',
      rubro:'Maderas',
      familia: 'Placas',
      categoria: 'MDF',
      subcategoria: '15mm',
      precio: 95	  
    },
    {
      id: '3',
      codigo: '',
      nombre: 'Fenolico OSB 18mm',
      rubro:'Maderas',
      familia: 'Placas',
      categoria: 'Fenolicos',
      subcategoria: '18mm',
      precio: 100,
      img: '',
      img_tumb: ''	  	  
    },
    {
      id: '4',
      codigo: '',
      nombre: 'Aglomerado Crudo 18mm',
      rubro:'Maderas',
      familia: 'Placas',
      categoria: 'Aglomerados',
      subcategoria: '18mm',
      precio: 180,
      img: '',
      img_tumb: ''	  	  
    },
    {
      id: '5',
      codigo: '',
      nombre: 'Fenolico 15mm',
      rubro:'Maderas',
      familia: 'Placas',
      categoria: 'Fenolicos',
      subcategoria: '15mm',
      precio: 120,
      img: '',
      img_tumb: ''	  	  
    },
    {
      id: '6',
      codigo: '',
      nombre: 'Machimbre 3/4"',
      rubro:'Maderas',
      familia: 'Maderas',
      categoria: 'Machimbres',
      subcategoria: '3/4"',
      precio: 90,
      img: '',
      img_tumb: ''	  	  
    },
    {
      id: '7',
      codigo: '',
      nombre: 'Machimbre 1/2"',
      rubro:'Maderas',
      familia: 'Maderas',
      categoria: 'Machimbres',
      subcategoria: '1/2"',
      precio: 150,
      img: '',
      img_tumb: ''	  	  
    },
    {
      id: '8',
      codigo: '',
      nombre: 'Viga Pino Laminada 3x8',
      rubro:'Maderas',
      familia: 'Maderas',
      categoria: 'Vigas',
      subcategoria: 'Laminadas',
      precio: 150,
      img: '',
      img_tumb: ''	  	  
    },
    {
      id: '9',
      codigo: '',
      nombre: 'Viga Pino Maciza 4x8',
      rubro:'Maderas',
      familia: 'Maderas',
      categoria: 'Vigas',
      subcategoria: 'Macizas',
      precio: 150,
      img: '',
      img_tumb: ''	  	  
    },
    {
      id: '10',
      codigo: '',
      nombre: 'Corredera Telescopica 40cm',
      rubro:'Ferreteria',
      familia: 'Accesorios',
      categoria: 'Correderas',
      subcategoria: 'Telescopicas',
      precio: 150,
      img: '',
      img_tumb: ''	  	  
    },
    {
      id: '11',
      codigo: '',
      nombre: 'Corredera Telescopica 40cm cierre suave',
      rubro:'Ferreteria',
      familia: 'Accesorios',
      categoria: 'Correderas',
      subcategoria: 'Telescopicas',
      precio: 150,
      img: '',
      img_tumb: ''	  	  
    },
    {
      id: '12',
      codigo: '',
      nombre: 'Bisagra Codo 0 35mm',
      rubro:'Ferreteria',
      familia: 'Accesorios',
      categoria: 'Bisagras',
      subcategoria: 'Cazoletas',
      precio: 150,
      img: '',
      img_tumb: ''	  	  
    },
    {
      id: '13',
      codigo: '',
      nombre: 'Bisagra Codo 15 35mm',
      rubro:'Ferreteria',
      familia: 'Accesorios',
      categoria: 'Bisagras',
      subcategoria: 'Cazoletas',
      precio: 150,
      img: '',
      img_tumb: ''	  	  
    },
    {
      id: '14',
      codigo: '',
      nombre: 'Bisagra Codo 0 26mm',
      rubro:'Ferreteria',
      familia: 'Accesorios',
      categoria: 'Bisagras',
      subcategoria: 'Cazoletas',
      precio: 150,
      img: '',
      img_tumb: ''	  	  
    }
];